package config

import (
	"myapp/logger"
	"os"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

//Generated By github.com/david-yappeter/GormCrudGenerator

var dsn = os.Getenv("POSTGRE_DSN")

func ConnectGorm() *gorm.DB {
	db, err := gorm.Open(postgres.Open(dsn), logger.InitConfig())

	if err != nil {
		panic("Fail to Connect Database")
	}

	return db
}
